[package]
name = "proptest-rust"
version = "0.1.0"
edition = "2024"

[dependencies]
byteorder = "1.5.0"
paste = "1.0.15"
proptest-derive = "0.7.0"
uuid = "1.19.0"
varint-rs = "2.2.0"

[dev-dependencies]
proptest = "1.9.0"
